<?php

$array = array(
    "England, UK", 
"Bath and North East Somerset, UK", 
"Bedford, UK", 
"Bedford, UK", 
"Blackburn with Darwen, UK", 
"Blackpool, UK", 
"Bournemouth, UK", 
"Bracknell Forest, UK", 
"Sandhurst, UK", 
"Brighton and Hove, UK", 
"Brighton, UK", 
"Hove, UK", 
"Bristol, UK", 
"Buckinghamshire, UK", 
"Aylesbury Vale, UK", 
"Aylesbury, UK", 
"Chiltern, UK", 
"Amersham, UK", 
"Chalfont St. Giles, UK", 
"South Bucks, UK", 
"Beaconsfield, UK", 
"Stoke Poges, UK", 
"Wycombe, UK", 
"High Wycombe, UK", 
"Marlow, UK", 
"Cambridgeshire, UK", 
"East Cambridgeshire, UK", 
"Ely, UK", 
"Fenland, UK", 
"Wisbech, UK", 
"Huntingdonshire, UK", 
"Huntingdon, UK", 
"Ramsey, UK", 
"St. Ives, UK", 
"South Cambridgeshire, UK", 
"Cambridge, UK", 
"Central Bedfordshire, UK", 
"Ampthill, UK", 
"Dunstable, UK", 
"Cheshire East, UK", 
"Congleton, UK", 
"Crewe, UK", 
"Knutsford, UK", 
"Macclesfield, UK", 
"Nantwich, UK", 
"Cheshire West and Chester, UK", 
"Chester, UK", 
"Northwich, UK", 
"Cornwall, UK", 
"Bodmin, UK", 
"Falmouth, UK", 
"Fowey, UK", 
"Helston, UK", 
"Launceston, UK", 
"Looe, UK", 
"Lostwithiel, UK", 
"Newquay, UK", 
"Penryn, UK", 
"Penzance, UK", 
"St. Austell, UK", 
"Saltash, UK", 
"Tintagel, UK", 
"Truro, UK", 
"Cumbria, UK", 
"Allerdale, UK", 
"Cockermouth, UK", 
"Keswick, UK", 
"Workington, UK", 
"Barrow-in-Furness, UK", 
"Carlisle, UK", 
"Copeland, UK", 
"Whitehaven, UK", 
"Eden, UK", 
"Penrith, UK", 
"South Lakeland, UK", 
"Grasmere, UK", 
"Kendal, UK", 
"Darlington, UK", 
"Derby, UK", 
"Derbyshire, UK", 
"Amber Valley, UK", 
"Belper, UK", 
"Bolsover, UK", 
"Chesterfield, UK", 
"Derbyshire Dales, UK", 
"Ashbourne, UK", 
"Matlock, UK", 
"Erewash, UK", 
"High Peak, UK", 
"Buxton, UK", 
"North East Derbyshire, UK", 
"South Derbyshire, UK", 
"Repton (village), UK", 
"Devon, UK", 
"East Devon, UK", 
"Axminster, UK", 
"Exmouth, UK", 
"Sidmouth, UK", 
"Exeter, UK", 
"Mid Devon, UK", 
"Crediton, UK", 
"North Devon, UK", 
"Barnstaple, UK", 
"Lynton and Lynmouth, UK", 
"South Hams, UK", 
"Dartmouth, UK", 
"Totnes, UK", 
"Teignbridge, UK", 
"Ashburton, UK", 
"Dawlish, UK", 
"Newton Abbot, UK", 
"Teignmouth, UK", 
"Torridge, UK", 
"Bideford, UK", 
"West Devon, UK", 
"Okehampton, UK", 
"Dorset, UK", 
"Christchurch, UK", 
"East Dorset, UK", 
"Wimborne Minster, UK", 
"North Dorset, UK", 
"Purbeck, UK", 
"Corfe Castle, UK", 
"West Dorset, UK", 
"Dorchester, UK", 
"Lyme Regis, UK", 
"Weymouth and Portland, UK", 
"Durham, UK", 
"Barnard Castle, UK", 
"Chester-le-Street, UK", 
"Durham, UK", 
"East Riding of Yorkshire, UK", 
"Beverley, UK", 
"Goole, UK", 
"East Sussex, UK", 
"Eastbourne, UK", 
"Hastings, UK", 
"Lewes, UK", 
"Lewes, UK", 
"Newhaven, UK", 
"Rother, UK", 
"Battle, UK", 
"Bexhill, UK", 
"Rye, UK", 
"Winchelsea, UK", 
"Wealden, UK", 
"Crowborough, UK", 
"Herstmonceux, UK", 
"Pevensey, UK", 
"Essex, UK", 
"Basildon, UK", 
"Braintree, UK", 
"Brentwood, UK", 
"Castle Point, UK", 
"Chelmsford, UK", 
"Colchester, UK", 
"Epping Forest, UK", 
"Chigwell, UK", 
"Harlow, UK", 
"Maldon, UK", 
"Burnham-on-Crouch, UK", 
"Rochford, UK", 
"Tendring, UK", 
"Harwich, UK", 
"Uttlesford, UK", 
"Saffron Walden, UK", 
"Gloucestershire, UK", 
"Cheltenham, UK", 
"Cotswold, UK", 
"Cirencester, UK", 
"Forest of Dean, UK", 
"Gloucester, UK", 
"Stroud, UK", 
"Tewkesbury, UK", 
"Tewkesbury, UK", 
"Winchcombe, UK", 
"Greater London, UK", 
"Inner London, UK", 
"Camden, UK", 
"Bloomsbury, UK", 
"City of London, UK", 
"Smithfield (area), UK", 
"City of Westminster, UK", 
"Charing Cross, UK", 
"St. Marylebone, UK", 
"Soho, UK", 
"Hackney, UK", 
"Hammersmith and Fulham, UK", 
"Haringey, UK", 
"Islington, UK", 
"Clerkenwell, UK", 
"Kensington and Chelsea, UK", 
"Lambeth, UK", 
"Vauxhall, UK", 
"Lewisham, UK", 
"Newham, UK", 
"Southwark, UK", 
"Dulwich, UK", 
"Tower Hamlets, UK", 
"Limehouse, UK", 
"Wandsworth, UK", 
"Battersea, UK", 
"Outer London, UK", 
"Barking and Dagenham, UK", 
"Barnet, UK", 
"Bexley, UK", 
"Brent, UK", 
"Bromley, UK", 
"Croydon, UK", 
"Ealing, UK", 
"Enfield, UK", 
"Greenwich, UK", 
"Woolwich, UK", 
"Harrow, UK", 
"Havering, UK", 
"Hillingdon, UK", 
"Hounslow, UK", 
"Kingston upon Thames, UK", 
"Teddington, UK", 
"Merton, UK", 
"Wimbledon, UK", 
"Redbridge, UK", 
"Richmond upon Thames, UK", 
"Sutton, UK", 
"Waltham Forest, UK", 
"Greater Manchester, UK", 
"Bolton, UK", 
"Bury, UK", 
"Manchester, UK", 
"Oldham, UK", 
"Rochdale, UK", 
"Salford, UK", 
"Stockport, UK", 
"Tameside, UK", 
"Trafford, UK", 
"Wigan, UK", 
"Atherton, UK", 
"Halton, UK", 
"Runcorn, UK", 
"Widnes, UK", 
"Hampshire, UK", 
"Basingstoke and Deane, UK", 
"Silchester, UK", 
"East Hampshire, UK", 
"Alton, UK", 
"Eastleigh, UK", 
"Fareham, UK", 
"Gosport, UK", 
"Hart, UK", 
"Havant, UK", 
"New Forest, UK", 
"Rushmoor, UK", 
"Test Valley, UK", 
"Andover, UK", 
"Romsey, UK", 
"Winchester, UK", 
"Hartlepool (town and unitary authority), UK", 
"Herefordshire, UK", 
"Hereford, UK", 
"Leominster, UK", 
"Ross-on-Wye, UK", 
"Hertfordshire, UK", 
"Broxbourne, UK", 
"Dacorum, UK", 
"Berkhamsted, UK", 
"Hemel Hempstead, UK", 
"East Hertfordshire, UK", 
"Bishop’s Stortford, UK", 
"Hertford, UK", 
"Ware, UK", 
"Hertsmere, UK", 
"North Hertfordshire, UK", 
"Letchworth, UK", 
"St. Albans, UK", 
"Stevenage, UK", 
"Three Rivers, UK", 
"Watford, UK", 
"Welwyn Hatfield, UK", 
"Hatfield, UK", 
"Welwyn Garden City, UK", 
"Isle of Wight, UK", 
"Carisbrooke, UK", 
"Cowes, UK", 
"Freshwater, UK", 
"Newport, UK", 
"Ryde, UK", 
"Ventnor, UK", 
"Isles of Scilly, UK", 
"Hugh Town, UK", 
"Kent, UK", 
"Ashford, UK", 
"Canterbury, UK", 
"Herne Bay, UK", 
"Whitstable, UK", 
"Dartford, UK", 
"Dover, UK", 
"Deal, UK", 
"Dover, UK", 
"Sandwich, UK", 
"Gravesham, UK", 
"Gravesend, UK", 
"Maidstone, UK", 
"Sevenoaks, UK", 
"Edenbridge, UK", 
"Shepway, UK", 
"Folkestone, UK", 
"Hythe, UK", 
"Lydd, UK", 
"New Romney, UK", 
"Swale, UK", 
"Faversham, UK", 
"Thanet, UK", 
"Broadstairs and St. Peter’s, UK", 
"Margate, UK", 
"Ramsgate, UK", 
"Tonbridge and Malling, UK", 
"Tunbridge Wells, UK", 
"Royal Tunbridge Wells, UK", 
"Kingston upon Hull, UK", 
"Lancashire, UK", 
"Burnley, UK", 
"Chorley, UK", 
"Fylde, UK", 
"Hyndburn, UK", 
"Lancaster, UK", 
"Pendle, UK", 
"Preston, UK", 
"Walton-le-Dale, UK", 
"Ribble Valley, UK", 
"Rossendale, UK", 
"South Ribble, UK", 
"West Lancashire, UK", 
"Skelmersdale, UK", 
"Wyre, UK", 
"Leicester, UK", 
"Leicestershire, UK", 
"Blaby, UK", 
"Charnwood, UK", 
"Loughborough, UK", 
"Harborough, UK", 
"Market Harborough, UK", 
"Hinckley and Bosworth, UK", 
"Melton, UK", 
"North West Leicestershire, UK", 
"Oadby and Wigston, UK", 
"Lincolnshire, UK", 
"Boston, UK", 
"East Lindsey, UK", 
"Lincoln, UK", 
"North Kesteven, UK", 
"South Kesteven, UK", 
"Grantham, UK", 
"Stamford, UK", 
"South Holland, UK", 
"Crowland, UK", 
"West Lindsey, UK", 
"Gainsborough, UK", 
"Luton, UK", 
"Medway, UK", 
"Chatham, UK", 
"Gillingham, UK", 
"Rochester, UK", 
"Merseyside, UK", 
"Knowsley, UK", 
"Huyton, UK", 
"Liverpool, UK", 
"St. Helens, UK", 
"Sefton, UK", 
"Southport, UK", 
"Wirral, UK", 
"Birkenhead, UK", 
"Middlesbrough, UK", 
"Milton Keynes, UK", 
"Norfolk, UK", 
"Breckland, UK", 
"East Dereham, UK", 
"Thetford, UK", 
"Broadland, UK", 
"Great Yarmouth, UK", 
"King’s Lynn and West Norfolk, UK", 
"Castle Rising, UK", 
"King’s Lynn, UK", 
"Sandringham, UK", 
"North Norfolk, UK", 
"Norwich, UK", 
"South Norfolk, UK", 
"North East Lincolnshire, UK", 
"Cleethorpes, UK", 
"Grimsby, UK", 
"North Lincolnshire, UK", 
"Scunthorpe, UK", 
"North Somerset, UK", 
"Weston-super-Mare, UK", 
"North Yorkshire, UK", 
"Craven, UK", 
"Hambleton, UK", 
"Northallerton, UK", 
"Harrogate, UK", 
"Knaresborough, UK", 
"Ripon, UK", 
"Richmondshire, UK", 
"Richmond, UK", 
"Ryedale, UK", 
"Malton, UK", 
"Scarborough, UK", 
"Whitby, UK", 
"Selby, UK", 
"Northamptonshire, UK", 
"Corby, UK", 
"Daventry, UK", 
"East Northamptonshire, UK", 
"Oundle, UK", 
"Kettering, UK", 
"Northampton, UK", 
"South Northamptonshire, UK", 
"WellinUKorough, UK", 
"Northumberland, UK", 
"Bamburgh, UK", 
"Bedlington, UK", 
"Cramlington, UK", 
"Hexham, UK", 
"Morpeth, UK", 
"Warkworth, UK", 
"Nottingham, UK", 
"Nottinghamshire, UK", 
"Ashfield, UK", 
"Bassetlaw, UK", 
"Worksop, UK", 
"Broxtowe, UK", 
"Beeston and Stapleford, UK", 
"Gedling, UK", 
"Mansfield, UK", 
"Newark and Sherwood, UK", 
"Newark-on-Trent, UK", 
"Rushcliffe, UK", 
"West Bridgford, UK", 
"Oxfordshire, UK", 
"Cherwell, UK", 
"Banbury, UK", 
"Bicester, UK", 
"Oxford, UK", 
"South Oxfordshire, UK", 
"Henley-on-Thames, UK", 
"Vale of White Horse, UK", 
"Wantage, UK", 
"West Oxfordshire, UK", 
"Burford, UK", 
"Peterborough, UK", 
"Plymouth, UK", 
"Poole, UK", 
"Portsmouth, UK", 
"Reading, UK", 
"Redcar and Cleveland, UK", 
"Rutland, UK", 
"Uppingham, UK", 
"Shropshire, UK", 
"Bridgnorth, UK", 
"Ludlow, UK", 
"Much Wenlock, UK", 
"Oswestry, UK", 
"Shrewsbury, UK", 
"Stokesay, UK", 
"Slough, UK", 
"Somerset, UK", 
"Mendip, UK", 
"Glastonbury, UK", 
"Wells, UK", 
"Sedgemoor, UK", 
"Bridgwater, UK", 
"Cheddar, UK", 
"South Somerset, UK", 
"Ilchester, UK", 
"Langport, UK", 
"Taunton Deane, UK", 
"Taunton, UK", 
"Wellington, UK", 
"West Somerset, UK", 
"Dunster, UK", 
"Minehead, UK", 
"South Gloucestershire, UK", 
"Badminton, UK", 
"Kingswood, UK", 
"South Yorkshire, UK", 
"Barnsley, UK", 
"Doncaster, UK", 
"Adwick le Street, UK", 
"Rotherham, UK", 
"Sheffield, UK", 
"Southampton, UK", 
"Southend-on-Sea, UK", 
"Staffordshire, UK", 
"Cannock Chase, UK", 
"East Staffordshire, UK", 
"Burton upon Trent, UK", 
"Lichfield, UK", 
"Newcastle-under-Lyme, UK", 
"South Staffordshire, UK", 
"Stafford, UK", 
"Staffordshire Moorlands, UK", 
"Tamworth, UK", 
"Stockton-on-Tees, UK", 
"Stoke-on-Trent, UK", 
"Suffolk, UK", 
"Babergh, UK", 
"Sudbury, UK", 
"Forest Heath, UK", 
"Mildenhall, UK", 
"Newmarket, UK", 
"Ipswich, UK", 
"Mid Suffolk, UK", 
"St. Edmundsbury, UK", 
"Bury St. Edmunds, UK", 
"Suffolk Coastal, UK", 
"Dunwich, UK", 
"Felixstowe, UK", 
"Woodbridge, UK", 
"Waveney, UK", 
"Beccles, UK", 
"Lowestoft, UK", 
"Surrey, UK", 
"Elmbridge, UK", 
"Epsom and Ewell, UK", 
"Guildford, UK", 
"Mole Valley, UK", 
"Dorking, UK", 
"Reigate and Banstead, UK", 
"Runnymede, UK", 
"Spelthorne, UK", 
"Staines, UK", 
"Surrey Heath, UK", 
"Tandridge, UK", 
"Waverley, UK", 
"Haslemere, UK", 
"Woking, UK", 
"Swindon, UK", 
"Telford and Wrekin, UK", 
"Telford, UK", 
"Thurrock, UK", 
"Tilbury, UK", 
"Torbay, UK", 
"Brixham, UK", 
"Tyne and Wear, UK", 
"Gateshead, UK", 
"Felling (ward), UK", 
"Newcastle upon Tyne, UK", 
"Newburn, UK", 
"North Tyneside, UK", 
"Wallsend, UK", 
"South Tyneside, UK", 
"Jarrow, UK", 
"South Shields, UK", 
"Sunderland, UK", 
"Washington, UK", 
"Warrington, UK", 
"Warwickshire, UK", 
"North Warwickshire, UK", 
"Nuneaton and Bedworth, UK", 
"Bedworth, UK", 
"RuUKy, UK", 
"Stratford-on-Avon, UK", 
"Warwick, UK", 
"Royal Leamington Spa, UK", 
"Warwick, UK", 
"West Berkshire, UK", 
"Newbury, UK", 
"West Midlands, UK", 
"Birmingham, UK", 
"Coventry, UK", 
"Dudley, UK", 
"Sandwell, UK", 
"West Bromwich, UK", 
"Solihull, UK", 
"Walsall, UK", 
"Wolverhampton, UK", 
"West Sussex, UK", 
"Adur, UK", 
"Shoreham-by-Sea, UK", 
"Arun, UK", 
"Arundel, UK", 
"Bognor Regis, UK", 
"Chichester, UK", 
"Petworth, UK", 
"Crawley, UK", 
"Horsham, UK", 
"Mid Sussex, UK", 
"East Grinstead, UK", 
"Worthing, UK", 
"West Yorkshire, UK", 
"Bradford, UK", 
"Haworth, UK", 
"Keighley, UK", 
"Saltaire, UK", 
"Calderdale, UK", 
"Halifax, UK", 
"Todmorden, UK", 
"Kirklees, UK", 
"Dewsbury, UK", 
"Huddersfield, UK", 
"Leeds, UK", 
"Wakefield, UK", 
"Pontefract, UK", 
"Wiltshire, UK", 
"Amesbury, UK", 
"Bradford-on-Avon, UK", 
"Chippenham, UK", 
"Cricklade, UK", 
"Devizes, UK", 
"Malmesbury, UK", 
"Marlborough, UK", 
"Salisbury, UK", 
"Trowbridge, UK", 
"Westbury, UK", 
"Wilton, UK", 
"Windsor and Maidenhead, UK", 
"Ascot, UK", 
"Bray, UK", 
"Eton, UK", 
"Maidenhead, UK", 
"Windsor, UK", 
"Wokingham, UK", 
"Worcestershire, UK", 
"Bromsgrove, UK", 
"Malvern Hills, UK", 
"Great Malvern, UK", 
"Redditch, UK", 
"Worcester, UK", 
"Wychavon, UK", 
"Broadway, UK", 
"Droitwich, UK", 
"Evesham, UK", 
"Wyre Forest, UK", 
"Kidderminster, UK", 
"York, UK", 
"Northern Ireland, UK", 
"Antrim and Newtownabbey, UK", 
"Antrim, UK", 
"Newtownabbey, UK", 
"Ards and North Down, UK", 
"Newtownards, UK", 
"Bangor, UK", 
"Armagh, Banbridge, and Craigavon, UK", 
"Armagh, UK", 
"Banbridge, UK", 
"Dromore, UK", 
"Craigavon, UK", 
"Lurgan, UK", 
"Belfast, UK", 
"Stormont, UK", 
"Causeway Coast and Glens, UK", 
"Ballycastle, UK", 
"Ballymoney, UK", 
"Coleraine, UK", 
"Portrush, UK", 
"Limavady, UK", 
"Derry and Strabane, UK", 
"Londonderry, UK", 
"Strabane, UK", 
"Fermanagh and Omagh, UK", 
"Enniskillen, UK", 
"Omagh, UK", 
"Lisburn and Castlereagh, UK", 
"Lisburn, UK", 
"Mid and East Antrim, UK", 
"Ballymena, UK", 
"Carrickfergus, UK", 
"Larne, UK", 
"Mid Ulster, UK", 
"Cookstown, UK", 
"Dungannon, UK", 
"Magherafelt, UK", 
"Newry, Mourne, and Down, UK", 
"Downpatrick, UK", 
"Kilkeel, UK", 
"Newcastle, UK", 
"Newry, UK", 
"Scotland, UK", 
"Aberdeen, UK", 
"Aberdeenshire, UK", 
"Banff, UK", 
"Braemar, UK", 
"Cruden Bay, UK", 
"Peterhead, UK", 
"St. Fergus, UK", 
"Angus, UK", 
"Arbroath, UK", 
"Brechin, UK", 
"Forfar, UK", 
"Glamis, UK", 
"Montrose, UK", 
"Argyll and Bute, UK", 
"Campbeltown, UK", 
"Dunoon, UK", 
"Inveraray, UK", 
"Lochgilphead, UK", 
"Rothesay, UK", 
"Tarbert, UK", 
"Clackmannanshire, UK", 
"Dumfries and Galloway, UK", 
"Dumfries, UK", 
"Gretna Green, UK", 
"Kirkcudbright, UK", 
"Lochmaben, UK", 
"Whithorn, UK", 
"Dundee, UK", 
"East Ayrshire, UK", 
"Cumnock, UK", 
"Kilmarnock, UK", 
"Mauchline, UK", 
"East Dunbartonshire, UK", 
"Kirkintilloch, UK", 
"Milngavie, UK", 
"East Lothian, UK", 
"Dunbar, UK", 
"Haddington, UK", 
"East Renfrewshire, UK", 
"Edinburgh, UK", 
"Leith, UK", 
"Falkirk, UK", 
"Falkirk, UK", 
"Grangemouth, UK", 
"Fife, UK", 
"Buckhaven, UK", 
"Culross, UK", 
"Cupar, UK", 
"Dunfermline, UK", 
"Glenrothes, UK", 
"Kirkcaldy, UK", 
"Rosyth, UK", 
"St. Andrews, UK", 
"Glasgow, UK", 
"Highland, UK", 
"Alness, UK", 
"Cawdor, UK", 
"Cromarty, UK", 
"Fort William, UK", 
"Invergordon, UK", 
"Inverness, UK", 
"John o’Groats, UK", 
"Nigg, UK", 
"Thurso, UK", 
"Wick, UK", 
"Inverclyde, UK", 
"Greenock, UK", 
"Midlothian, UK", 
"Dalkeith, UK", 
"Moray, UK", 
"Elgin, UK", 
"Forres, UK", 
"Lossiemouth, UK", 
"North Ayrshire, UK", 
"Irvine, UK", 
"North Lanarkshire, UK", 
"Coatbridge, UK", 
"Cumbernauld, UK", 
"Motherwell and Wishaw, UK", 
"Orkney Islands, UK", 
"Kirkwall, UK", 
"Perth and Kinross, UK", 
"Dunkeld, UK", 
"Kinross, UK", 
"Perth, UK", 
"Scone, UK", 
"Renfrewshire, UK", 
"Paisley, UK", 
"Renfrew, UK", 
"Scottish Borders, UK", 
"Coldstream, UK", 
"Duns, UK", 
"Galashiels, UK", 
"Hawick, UK", 
"Jedburgh, UK", 
"Kelso, UK", 
"Melrose, UK", 
"Newtown St. Boswells, UK", 
"Peebles, UK", 
"Selkirk, UK", 
"Shetland Islands, UK", 
"Lerwick, UK", 
"Sullom Voe, UK", 
"South Ayrshire, UK", 
"Ayr, UK", 
"Alloway, UK", 
"Prestwick, UK", 
"South Lanarkshire, UK", 
"East Kilbride, UK", 
"Hamilton, UK", 
"Lanark, UK", 
"Stirling, UK", 
"Balquhidder, UK", 
"Bannockburn, UK", 
"Callander, UK", 
"Stirling, UK", 
"West Dunbartonshire, UK", 
"Clydebank, UK", 
"Dumbarton, UK", 
"West Lothian, UK", 
"Linlithgow, UK", 
"Livingston, UK", 
"Western Isles, UK", 
"Stornoway, UK", 
"Wales, UK", 
"Blaenau Gwent, UK", 
"Abertillery, UK", 
"Ebbw Vale, UK", 
"Bridgend, UK", 
"Bridgend, UK", 
"Porthcawl, UK", 
"Caerphilly, UK", 
"Caerphilly, UK", 
"Gelligaer, UK", 
"Cardiff, UK", 
"Llandaff, UK", 
"Carmarthenshire, UK", 
"Carmarthen, UK", 
"Llanelli, UK", 
"Ceredigion, UK", 
"Aberystwyth, UK", 
"Cardigan, UK", 
"Conwy, UK", 
"Colwyn Bay, UK", 
"Conwy, UK", 
"Llandudno, UK", 
"Denbighshire, UK", 
"Denbigh, UK", 
"Rhyl, UK", 
"St. Asaph, UK", 
"Flintshire, UK", 
"Hawarden, UK", 
"Holywell, UK", 
"Gwynedd, UK", 
"Bala, UK", 
"Bangor, UK", 
"Caernarfon, UK", 
"Harlech, UK", 
"Isle of Anglesey, UK", 
"Holyhead, UK", 
"Llangefni, UK", 
"Merthyr Tydfil, UK", 
"Monmouthshire, UK", 
"Abergavenny, UK", 
"Chepstow, UK", 
"Monmouth, UK", 
"Usk, UK", 
"Neath Port Talbot, UK", 
"Margam, UK", 
"Neath, UK", 
"Pontardawe, UK", 
"Port Talbot, UK", 
"Newport, UK", 
"Caerleon, UK", 
"Pembrokeshire, UK", 
"Haverfordwest, UK", 
"Milford Haven, UK", 
"Pembroke, UK", 
"St. David’s, UK", 
"Tenby, UK", 
"Powys, UK", 
"Brecon, UK", 
"Builth Wells, UK", 
"Llandrindod Wells, UK", 
"Montgomery, UK", 
"Newtown, UK", 
"Welshpool, UK", 
"Rhondda Cynon Taf, UK", 
"Aberdare, UK", 
"Hirwaun, UK", 
"Llantrisant, UK", 
"Mountain Ash, UK", 
"Pontypridd, UK", 
"Swansea, UK", 
"Swansea, UK", 
"Torfaen, UK", 
"Cwmbran, UK", 
"Pontypool, UK", 
"Vale of Glamorgan, UK", 
"Barry, UK", 
"Cowbridge, UK", 
"Llantwit Major, UK", 
"Wrexham, UK", 
);


$usArray = array(
    "Alabama, United States",
    "Alexander City, United States",
    "Andalusia, United States",
    "Anniston, United States",
    "Athens, United States",
    "Atmore, United States",
    "Auburn, United States",
    "Bessemer, United States",
    "Birmingham, United States",
    "Chickasaw, United States",
    "Clanton, United States",
    "Cullman, United States",
    "Decatur, United States",
    "Demopolis, United States",
    "Dothan, United States",
    "Enterprise, United States",
    "Eufaula, United States",
    "Florence, United States",
    "Fort Payne, United States",
    "Gadsden, United States",
    "Greenville, United States",
    "Guntersville, United States",
    "Huntsville, United States",
    "Jasper, United States",
    "Marion, United States",
    "Mobile, United States",
    "Montgomery, United States",
    "Opelika, United States",
    "Ozark, United States",
    "Phenix City, United States",
    "Prichard, United States",
    "Scottsboro, United States",
    "Selma, United States",
    "Sheffield, United States",
    "Sylacauga, United States",
    "Talladega, United States",
    "Troy, United States",
    "Tuscaloosa, United States",
    "Tuscumbia, United States",
    "Tuskegee, United States",
    "Alaska, United States",
    "Anchorage, United States",
    "Cordova, United States",
    "Fairbanks, United States",
    "Haines, United States",
    "Homer, United States",
    "Juneau, United States",
    "Ketchikan, United States",
    "Kodiak, United States",
    "Kotzebue, United States",
    "Nome, United States",
    "Palmer, United States",
    "Seward, United States",
    "Sitka, United States",
    "Skagway, United States",
    "Valdez, United States",
    "Arizona, United States",
    "Ajo, United States",
    "Avondale, United States",
    "Bisbee, United States",
    "Casa Grande, United States",
    "Chandler, United States",
    "Clifton, United States",
    "Douglas, United States",
    "Flagstaff, United States",
    "Florence, United States",
    "Gila Bend, United States",
    "Glendale, United States",
    "Globe, United States",
    "Kingman, United States",
    "Lake Havasu City, United States",
    "Mesa, United States",
    "Nogales, United States",
    "Oraibi, United States",
    "Phoenix, United States",
    "Prescott, United States",
    "Scottsdale, United States",
    "Sierra Vista, United States",
    "Tempe, United States",
    "Tombstone, United States",
    "Tucson, United States",
    "Walpi, United States",
    "Window Rock, United States",
    "Winslow, United States",
    "Yuma, United States",
    "Arkansas, United States",
    "Arkadelphia, United States",
    "Arkansas Post, United States",
    "Batesville, United States",
    "Benton, United States",
    "Blytheville, United States",
    "Camden, United States",
    "Conway, United States",
    "Crossett, United States",
    "El Dorado, United States",
    "Fayetteville, United States",
    "Forrest City, United States",
    "Fort Smith, United States",
    "Harrison, United States",
    "Helena, United States",
    "Hope, United States",
    "Hot Springs, United States",
    "Jacksonville, United States",
    "Jonesboro, United States",
    "Little Rock, United States",
    "Magnolia, United States",
    "Morrilton, United States",
    "Newport, United States",
    "North Little Rock, United States",
    "Osceola, United States",
    "Pine Bluff, United States",
    "Rogers, United States",
    "Searcy, United States",
    "Stuttgart, United States",
    "Van Buren, United States",
    "West Memphis, United States",
    "California, United States",
    "Alameda, United States",
    "Alhambra, United States",
    "Anaheim, United States",
    "Antioch, United States",
    "Arcadia, United States",
    "Bakersfield, United States",
    "Barstow, United States",
    "Belmont, United States",
    "Berkeley, United States",
    "Beverly Hills, United States",
    "Brea, United States",
    "Buena Park, United States",
    "Burbank, United States",
    "Calexico, United States",
    "Calistoga, United States",
    "Carlsbad, United States",
    "Carmel, United States",
    "Chico, United States",
    "Chula Vista, United States",
    "Claremont, United States",
    "Compton, United States",
    "Concord, United States",
    "Corona, United States",
    "Coronado, United States",
    "Costa Mesa, United States",
    "Culver City, United States",
    "Daly City, United States",
    "Davis, United States",
    "Downey, United States",
    "El Centro, United States",
    "El Cerrito, United States",
    "El Monte, United States",
    "Escondido, United States",
    "Eureka, United States",
    "Fairfield, United States",
    "Fontana, United States",
    "Fremont, United States",
    "Fresno, United States",
    "Fullerton, United States",
    "Garden Grove, United States",
    "Glendale, United States",
    "Hayward, United States",
    "Hollywood, United States",
    "Huntington Beach, United States",
    "Indio, United States",
    "Inglewood, United States",
    "Irvine, United States",
    "La Habra, United States",
    "Laguna Beach, United States",
    "Lancaster, United States",
    "Livermore, United States",
    "Lodi, United States",
    "Lompoc, United States",
    "Long Beach, United States",
    "Los Angeles, United States",
    "Malibu, United States",
    "Martinez, United States",
    "Marysville, United States",
    "Menlo Park, United States",
    "Merced, United States",
    "Modesto, United States",
    "Monterey, United States",
    "Mountain View, United States",
    "Napa, United States",
    "Needles, United States",
    "Newport Beach, United States",
    "Norwalk, United States",
    "Novato, United States",
    "Oakland, United States",
    "Oceanside, United States",
    "Ojai, United States",
    "Ontario, United States",
    "Orange, United States",
    "Oroville, United States",
    "Oxnard, United States",
    "Pacific Grove, United States",
    "Palm Springs, United States",
    "Palmdale, United States",
    "Palo Alto, United States",
    "Pasadena, United States",
    "Petaluma, United States",
    "Pomona, United States",
    "Port Hueneme, United States",
    "Rancho Cucamonga, United States",
    "Red Bluff, United States",
    "Redding, United States",
    "Redlands, United States",
    "Redondo Beach, United States",
    "Redwood City, United States",
    "Richmond, United States",
    "Riverside, United States",
    "Roseville, United States",
    "Sacramento, United States",
    "Salinas, United States",
    "San Bernardino, United States",
    "San Clemente, United States",
    "San Diego, United States",
    "San Fernando, United States",
    "San Francisco, United States",
    "San Gabriel, United States",
    "San Jose, United States",
    "San Juan Capistrano, United States",
    "San Leandro, United States",
    "San Luis Obispo, United States",
    "San Marino, United States",
    "San Mateo, United States",
    "San Pedro, United States",
    "San Rafael, United States",
    "San Simeon, United States",
    "Santa Ana, United States",
    "Santa Barbara, United States",
    "Santa Clara, United States",
    "Santa Clarita, United States",
    "Santa Cruz, United States",
    "Santa Monica, United States",
    "Santa Rosa, United States",
    "Sausalito, United States",
    "Simi Valley, United States",
    "Sonoma, United States",
    "South San Francisco, United States",
    "Stockton, United States",
    "Sunnyvale, United States",
    "Susanville, United States",
    "Thousand Oaks, United States",
    "Torrance, United States",
    "Turlock, United States",
    "Ukiah, United States",
    "Vallejo, United States",
    "Ventura, United States",
    "Victorville, United States",
    "Visalia, United States",
    "Walnut Creek, United States",
    "Watts, United States",
    "West Covina, United States",
    "Whittier, United States",
    "Woodland, United States",
    "Yorba Linda, United States",
    "Yuba City, United States",
    "Colorado, United States",
    "Alamosa, United States",
    "Aspen, United States",
    "Aurora, United States",
    "Boulder, United States",
    "Breckenridge, United States",
    "Brighton, United States",
    "Canon City, United States",
    "Central City, United States",
    "Climax, United States",
    "Colorado Springs, United States",
    "Cortez, United States",
    "Cripple Creek, United States",
    "Denver, United States",
    "Durango, United States",
    "Englewood, United States",
    "Estes Park, United States",
    "Fort Collins, United States",
    "Fort Morgan, United States",
    "Georgetown, United States",
    "Glenwood Springs, United States",
    "Golden, United States",
    "Grand Junction, United States",
    "Greeley, United States",
    "Gunnison, United States",
    "La Junta, United States",
    "Leadville, United States",
    "Littleton, United States",
    "Longmont, United States",
    "Loveland, United States",
    "Montrose, United States",
    "Ouray, United States",
    "Pagosa Springs, United States",
    "Pueblo, United States",
    "Silverton, United States",
    "Steamboat Springs, United States",
    "Sterling, United States",
    "Telluride, United States",
    "Trinidad, United States",
    "Vail, United States",
    "Walsenburg, United States",
    "Westminster, United States",
    "Connecticut, United States",
    "Ansonia, United States",
    "Berlin, United States",
    "Bloomfield, United States",
    "Branford, United States",
    "Bridgeport, United States",
    "Bristol, United States",
    "Coventry, United States",
    "Danbury, United States",
    "Darien, United States",
    "Derby, United States",
    "East Hartford, United States",
    "East Haven, United States",
    "Enfield, United States",
    "Fairfield, United States",
    "Farmington, United States",
    "Greenwich, United States",
    "Groton, United States",
    "Guilford, United States",
    "Hamden, United States",
    "Hartford, United States",
    "Lebanon, United States",
    "Litchfield, United States",
    "Manchester, United States",
    "Mansfield, United States",
    "Meriden, United States",
    "Middletown, United States",
    "Milford, United States",
    "Mystic, United States",
    "Naugatuck, United States",
    "New Britain, United States",
    "New Haven, United States",
    "New London, United States",
    "North Haven, United States",
    "Norwalk, United States",
    "Norwich, United States",
    "Old Saybrook, United States",
    "Orange, United States",
    "Seymour, United States",
    "Shelton, United States",
    "Simsbury, United States",
    "Southington, United States",
    "Stamford, United States",
    "Stonington, United States",
    "Stratford, United States",
    "Torrington, United States",
    "Wallingford, United States",
    "Waterbury, United States",
    "Waterford, United States",
    "Watertown, United States",
    "West Hartford, United States",
    "West Haven, United States",
    "Westport, United States",
    "Wethersfield, United States",
    "Willimantic, United States",
    "Windham, United States",
    "Windsor, United States",
    "Windsor Locks, United States",
    "Winsted, United States",
    "Delaware, United States",
    "Dover, United States",
    "Lewes, United States",
    "Milford, United States",
    "New Castle, United States",
    "Newark, United States",
    "Smyrna, United States",
    "Wilmington, United States",
    "Florida, United States",
    "Apalachicola, United States",
    "Bartow, United States",
    "Belle Glade, United States",
    "Boca Raton, United States",
    "Bradenton, United States",
    "Cape Coral, United States",
    "Clearwater, United States",
    "Cocoa Beach, United States",
    "Cocoa-Rockledge, United States",
    "Coral Gables, United States",
    "Daytona Beach, United States",
    "De Land, United States",
    "Deerfield Beach, United States",
    "Delray Beach, United States",
    "Fernandina Beach, United States",
    "Fort Lauderdale, United States",
    "Fort Myers, United States",
    "Fort Pierce, United States",
    "Fort Walton Beach, United States",
    "Gainesville, United States",
    "Hallandale Beach, United States",
    "Hialeah, United States",
    "Hollywood, United States",
    "Homestead, United States",
    "Jacksonville, United States",
    "Key West, United States",
    "Lake City, United States",
    "Lake Wales, United States",
    "Lakeland, United States",
    "Largo, United States",
    "Melbourne, United States",
    "Miami, United States",
    "Miami Beach, United States",
    "Naples, United States",
    "New Smyrna Beach, United States",
    "Ocala, United States",
    "Orlando, United States",
    "Ormond Beach, United States",
    "Palatka, United States",
    "Palm Bay, United States",
    "Palm Beach, United States",
    "Panama City, United States",
    "Pensacola, United States",
    "Pompano Beach, United States",
    "Saint Augustine, United States",
    "Saint Petersburg, United States",
    "Sanford, United States",
    "Sarasota, United States",
    "Sebring, United States",
    "Tallahassee, United States",
    "Tampa, United States",
    "Tarpon Springs, United States",
    "Titusville, United States",
    "Venice, United States",
    "West Palm Beach, United States",
    "White Springs, United States",
    "Winter Haven, United States",
    "Winter Park, United States",
    "Georgia, United States",
    "Albany, United States",
    "Americus, United States",
    "Andersonville, United States",
    "Athens, United States",
    "Atlanta, United States",
    "Augusta, United States",
    "Bainbridge, United States",
    "Blairsville, United States",
    "Brunswick, United States",
    "Calhoun, United States",
    "Carrollton, United States",
    "Columbus, United States",
    "Dahlonega, United States",
    "Dalton, United States",
    "Darien, United States",
    "Decatur, United States",
    "Douglas, United States",
    "East Point, United States",
    "Fitzgerald, United States",
    "Fort Valley, United States",
    "Gainesville, United States",
    "La Grange, United States",
    "Macon, United States",
    "Marietta, United States",
    "Milledgeville, United States",
    "Plains, United States",
    "Rome, United States",
    "Savannah, United States",
    "Toccoa, United States",
    "Valdosta, United States",
    "Warm Springs, United States",
    "Warner Robins, United States",
    "Washington, United States",
    "Waycross, United States",
    "Hawaii, United States",
    "Hanalei, United States",
    "Hilo, United States",
    "Honaunau, United States",
    "Honolulu, United States",
    "Kahului, United States",
    "Kaneohe, United States",
    "Kapaa, United States",
    "Kawaihae, United States",
    "Lahaina, United States",
    "Laie, United States",
    "Wahiawa, United States",
    "Wailuku, United States",
    "Waimea, United States",
    "Idaho, United States",
    "Blackfoot, United States",
    "Boise, United States",
    "Bonners Ferry, United States",
    "Caldwell, United States",
    "Coeur d’Alene, United States",
    "Idaho City, United States",
    "Idaho Falls, United States",
    "Kellogg, United States",
    "Lewiston, United States",
    "Moscow, United States",
    "Nampa, United States",
    "Pocatello, United States",
    "Priest River, United States",
    "Rexburg, United States",
    "Sun Valley, United States",
    "Twin Falls, United States",
    "Illinois, United States",
    "Alton, United States",
    "Arlington Heights, United States",
    "Arthur, United States",
    "Aurora, United States",
    "Belleville, United States",
    "Belvidere, United States",
    "Bloomington, United States",
    "Brookfield, United States",
    "Cahokia, United States",
    "Cairo, United States",
    "Calumet City, United States",
    "Canton, United States",
    "Carbondale, United States",
    "Carlinville, United States",
    "Carthage, United States",
    "Centralia, United States",
    "Champaign, United States",
    "Charleston, United States",
    "Chester, United States",
    "Chicago, United States",
    "Chicago Heights, United States",
    "Cicero, United States",
    "Collinsville, United States",
    "Danville, United States",
    "Decatur, United States",
    "DeKalb, United States",
    "Des Plaines, United States",
    "Dixon, United States",
    "East Moline, United States",
    "East Saint Louis, United States",
    "Effingham, United States",
    "Elgin, United States",
    "Elmhurst, United States",
    "Evanston, United States",
    "Freeport, United States",
    "Galena, United States",
    "Galesburg, United States",
    "Glen Ellyn, United States",
    "Glenview, United States",
    "Granite City, United States",
    "Harrisburg, United States",
    "Herrin, United States",
    "Highland Park, United States",
    "Jacksonville, United States",
    "Joliet, United States",
    "Kankakee, United States",
    "Kaskaskia, United States",
    "Kewanee, United States",
    "La Salle, United States",
    "Lake Forest, United States",
    "Libertyville, United States",
    "Lincoln, United States",
    "Lisle, United States",
    "Lombard, United States",
    "Macomb, United States",
    "Mattoon, United States",
    "Moline, United States",
    "Monmouth, United States",
    "Mount Vernon, United States",
    "Mundelein, United States",
    "Naperville, United States",
    "Nauvoo, United States",
    "Normal, United States",
    "North Chicago, United States",
    "Oak Park, United States",
    "Oregon, United States",
    "Ottawa, United States",
    "Palatine, United States",
    "Park Forest, United States",
    "Park Ridge, United States",
    "Pekin, United States",
    "Peoria, United States",
    "Petersburg, United States",
    "Pontiac, United States",
    "Quincy, United States",
    "Rantoul, United States",
    "River Forest, United States",
    "Rock Island, United States",
    "Rockford, United States",
    "Salem, United States",
    "Shawneetown, United States",
    "Skokie, United States",
    "South Holland, United States",
    "Springfield, United States",
    "Streator, United States",
    "Summit, United States",
    "Urbana, United States",
    "Vandalia, United States",
    "Virden, United States",
    "Waukegan, United States",
    "Wheaton, United States",
    "Wilmette, United States",
    "Winnetka, United States",
    "Wood River, United States",
    "Zion, United States",
    "Indiana, United States",
    "Anderson, United States",
    "Bedford, United States",
    "Bloomington, United States",
    "Columbus, United States",
    "Connersville, United States",
    "Corydon, United States",
    "Crawfordsville, United States",
    "East Chicago, United States",
    "Elkhart, United States",
    "Elwood, United States",
    "Evansville, United States",
    "Fort Wayne, United States",
    "French Lick, United States",
    "Gary, United States",
    "Geneva, United States",
    "Goshen, United States",
    "Greenfield, United States",
    "Hammond, United States",
    "Hobart, United States",
    "Huntington, United States",
    "Indianapolis, United States",
    "Jeffersonville, United States",
    "Kokomo, United States",
    "Lafayette, United States",
    "Madison, United States",
    "Marion, United States",
    "Michigan City, United States",
    "Mishawaka, United States",
    "Muncie, United States",
    "Nappanee, United States",
    "Nashville, United States",
    "New Albany, United States",
    "New Castle, United States",
    "New Harmony, United States",
    "Peru, United States",
    "Plymouth, United States",
    "Richmond, United States",
    "Santa Claus, United States",
    "Shelbyville, United States",
    "South Bend, United States",
    "Terre Haute, United States",
    "Valparaiso, United States",
    "Vincennes, United States",
    "Wabash, United States",
    "West Lafayette, United States",
    "Iowa, United States",
    "Amana Colonies, United States",
    "Ames, United States",
    "Boone, United States",
    "Burlington, United States",
    "Cedar Falls, United States",
    "Cedar Rapids, United States",
    "Charles City, United States",
    "Cherokee, United States",
    "Clinton, United States",
    "Council Bluffs, United States",
    "Davenport, United States",
    "Des Moines, United States",
    "Dubuque, United States",
    "Estherville, United States",
    "Fairfield, United States",
    "Fort Dodge, United States",
    "Grinnell, United States",
    "Indianola, United States",
    "Iowa City, United States",
    "Keokuk, United States",
    "Mason City, United States",
    "Mount Pleasant, United States",
    "Muscatine, United States",
    "Newton, United States",
    "Oskaloosa, United States",
    "Ottumwa, United States",
    "Sioux City, United States",
    "Waterloo, United States",
    "Webster City, United States",
    "West Des Moines, United States",
    "Kansas, United States",
    "Abilene, United States",
    "Arkansas City, United States",
    "Atchison, United States",
    "Chanute, United States",
    "Coffeyville, United States",
    "Council Grove, United States",
    "Dodge City, United States",
    "Emporia, United States",
    "Fort Scott, United States",
    "Garden City, United States",
    "Great Bend, United States",
    "Hays, United States",
    "Hutchinson, United States",
    "Independence, United States",
    "Junction City, United States",
    "Kansas City, United States",
    "Lawrence, United States",
    "Leavenworth, United States",
    "Liberal, United States",
    "Manhattan, United States",
    "McPherson, United States",
    "Medicine Lodge, United States",
    "Newton, United States",
    "Olathe, United States",
    "Osawatomie, United States",
    "Ottawa, United States",
    "Overland Park, United States",
    "Pittsburg, United States",
    "Salina, United States",
    "Shawnee, United States",
    "Smith Center, United States",
    "Topeka, United States",
    "Wichita, United States",
    "Kentucky, United States",
    "Ashland, United States",
    "Barbourville, United States",
    "Bardstown, United States",
    "Berea, United States",
    "Boonesborough, United States",
    "Bowling Green, United States",
    "Campbellsville, United States",
    "Covington, United States",
    "Danville, United States",
    "Elizabethtown, United States",
    "Frankfort, United States",
    "Harlan, United States",
    "Harrodsburg, United States",
    "Hazard, United States",
    "Henderson, United States",
    "Hodgenville, United States",
    "Hopkinsville, United States",
    "Lexington, United States",
    "Louisville, United States",
    "Mayfield, United States",
    "Maysville, United States",
    "Middlesboro, United States",
    "Newport, United States",
    "Owensboro, United States",
    "Paducah, United States",
    "Paris, United States",
    "Richmond, United States",
    "Louisiana, United States",
    "Abbeville, United States",
    "Alexandria, United States",
    "Bastrop, United States",
    "Baton Rouge, United States",
    "Bogalusa, United States",
    "Bossier City, United States",
    "Gretna, United States",
    "Houma, United States",
    "Lafayette, United States",
    "Lake Charles, United States",
    "Monroe, United States",
    "Morgan City, United States",
    "Natchitoches, United States",
    "New Iberia, United States",
    "New Orleans, United States",
    "Opelousas, United States",
    "Ruston, United States",
    "Saint Martinville, United States",
    "Shreveport, United States",
    "Thibodaux, United States",
    "Maine, United States",
    "Auburn, United States",
    "Augusta, United States",
    "Bangor, United States",
    "Bar Harbor, United States",
    "Bath, United States",
    "Belfast, United States",
    "Biddeford, United States",
    "Boothbay Harbor, United States",
    "Brunswick, United States",
    "Calais, United States",
    "Caribou, United States",
    "Castine, United States",
    "Eastport, United States",
    "Ellsworth, United States",
    "Farmington, United States",
    "Fort Kent, United States",
    "Gardiner, United States",
    "Houlton, United States",
    "Kennebunkport, United States",
    "Kittery, United States",
    "Lewiston, United States",
    "Lubec, United States",
    "Machias, United States",
    "Orono, United States",
    "Portland, United States",
    "Presque Isle, United States",
    "Rockland, United States",
    "Rumford, United States",
    "Saco, United States",
    "Scarborough, United States",
    "Waterville, United States",
    "York, United States",
    "Maryland, United States",
    "Aberdeen, United States",
    "Annapolis, United States",
    "Baltimore, United States",
    "Bethesda-Chevy Chase, United States",
    "Bowie, United States",
    "Cambridge, United States",
    "Catonsville, United States",
    "College Park, United States",
    "Columbia, United States",
    "Cumberland, United States",
    "Easton, United States",
    "Elkton, United States",
    "Emmitsburg, United States",
    "Frederick, United States",
    "Greenbelt, United States",
    "Hagerstown, United States",
    "Hyattsville, United States",
    "Laurel, United States",
    "Oakland, United States",
    "Ocean City, United States",
    "Rockville, United States",
    "Saint Marys City, United States",
    "Salisbury, United States",
    "Silver Spring, United States",
    "Takoma Park, United States",
    "Towson, United States",
    "Westminster, United States",
    "Massachusetts, United States",
    "Abington, United States",
    "Adams, United States",
    "Amesbury, United States",
    "Amherst, United States",
    "Andover, United States",
    "Arlington, United States",
    "Athol, United States",
    "Attleboro, United States",
    "Barnstable, United States",
    "Bedford, United States",
    "Beverly, United States",
    "Boston, United States",
    "Bourne, United States",
    "Braintree, United States",
    "Brockton, United States",
    "Brookline, United States",
    "Cambridge, United States",
    "Canton, United States",
    "Charlestown, United States",
    "Chelmsford, United States",
    "Chelsea, United States",
    "Chicopee, United States",
    "Clinton, United States",
    "Cohasset, United States",
    "Concord, United States",
    "Danvers, United States",
    "Dartmouth, United States",
    "Dedham, United States",
    "Dennis, United States",
    "Duxbury, United States",
    "Eastham, United States",
    "Edgartown, United States",
    "Everett, United States",
    "Fairhaven, United States",
    "Fall River, United States",
    "Falmouth, United States",
    "Fitchburg, United States",
    "Framingham, United States",
    "Gloucester, United States",
    "Great Barrington, United States",
    "Greenfield, United States",
    "Groton, United States",
    "Harwich, United States",
    "Haverhill, United States",
    "Hingham, United States",
    "Holyoke, United States",
    "Hyannis, United States",
    "Ipswich, United States",
    "Lawrence, United States",
    "Lenox, United States",
    "Leominster, United States",
    "Lexington, United States",
    "Lowell, United States",
    "Ludlow, United States",
    "Lynn, United States",
    "Malden, United States",
    "Marblehead, United States",
    "Marlborough, United States",
    "Medford, United States",
    "Milton, United States",
    "Nahant, United States",
    "Natick, United States",
    "New Bedford, United States",
    "Newburyport, United States",
    "Newton, United States",
    "North Adams, United States",
    "Northampton, United States",
    "Norton, United States",
    "Norwood, United States",
    "Peabody, United States",
    "Pittsfield, United States",
    "Plymouth, United States",
    "Provincetown, United States",
    "Quincy, United States",
    "Randolph, United States",
    "Revere, United States",
    "Salem, United States",
    "Sandwich, United States",
    "Saugus, United States",
    "Somerville, United States",
    "South Hadley, United States",
    "Springfield, United States",
    "Stockbridge, United States",
    "Stoughton, United States",
    "Sturbridge, United States",
    "Sudbury, United States",
    "Taunton, United States",
    "Tewksbury, United States",
    "Truro, United States",
    "Watertown, United States",
    "Webster, United States",
    "Wellesley, United States",
    "Wellfleet, United States",
    "West Bridgewater, United States",
    "West Springfield, United States",
    "Westfield, United States",
    "Weymouth, United States",
    "Whitman, United States",
    "Williamstown, United States",
    "Woburn, United States",
    "Woods Hole, United States",
    "Worcester, United States",
    "Michigan, United States",
    "Adrian, United States",
    "Alma, United States",
    "Ann Arbor, United States",
    "Battle Creek, United States",
    "Bay City, United States",
    "Benton Harbor, United States",
    "Bloomfield Hills, United States",
    "Cadillac, United States",
    "Charlevoix, United States",
    "Cheboygan, United States",
    "Dearborn, United States",
    "Detroit, United States",
    "East Lansing, United States",
    "Eastpointe, United States",
    "Ecorse, United States",
    "Escanaba, United States",
    "Flint, United States",
    "Grand Haven, United States",
    "Grand Rapids, United States",
    "Grayling, United States",
    "Grosse Pointe, United States",
    "Hancock, United States",
    "Highland Park, United States",
    "Holland, United States",
    "Houghton, United States",
    "Interlochen, United States",
    "Iron Mountain, United States",
    "Ironwood, United States",
    "Ishpeming, United States",
    "Jackson, United States",
    "Kalamazoo, United States",
    "Lansing, United States",
    "Livonia, United States",
    "Ludington, United States",
    "Mackinaw City, United States",
    "Manistee, United States",
    "Marquette, United States",
    "Menominee, United States",
    "Midland, United States",
    "Monroe, United States",
    "Mount Clemens, United States",
    "Mount Pleasant, United States",
    "Muskegon, United States",
    "Niles, United States",
    "Petoskey, United States",
    "Pontiac, United States",
    "Port Huron, United States",
    "Royal Oak, United States",
    "Saginaw, United States",
    "Saint Ignace, United States",
    "Saint Joseph, United States",
    "Sault Sainte Marie, United States",
    "Traverse City, United States",
    "Trenton, United States",
    "Warren, United States",
    "Wyandotte, United States",
    "Ypsilanti, United States",
    "Minnesota, United States",
    "Albert Lea, United States",
    "Alexandria, United States",
    "Austin, United States",
    "Bemidji, United States",
    "Bloomington, United States",
    "Brainerd, United States",
    "Crookston, United States",
    "Duluth, United States",
    "Ely, United States",
    "Eveleth, United States",
    "Faribault, United States",
    "Fergus Falls, United States",
    "Hastings, United States",
    "Hibbing, United States",
    "International Falls, United States",
    "Little Falls, United States",
    "Mankato, United States",
    "Minneapolis, United States",
    "Moorhead, United States",
    "New Ulm, United States",
    "Northfield, United States",
    "Owatonna, United States",
    "Pipestone, United States",
    "Red Wing, United States",
    "Rochester, United States",
    "Saint Cloud, United States",
    "Saint Paul, United States",
    "Sauk Centre, United States",
    "South Saint Paul, United States",
    "Stillwater, United States",
    "Virginia, United States",
    "Willmar, United States",
    "Winona, United States",
    "Mississippi, United States",
    "Bay Saint Louis, United States",
    "Biloxi, United States",
    "Canton, United States",
    "Clarksdale, United States",
    "Columbia, United States",
    "Columbus, United States",
    "Corinth, United States",
    "Greenville, United States",
    "Greenwood, United States",
    "Grenada, United States",
    "Gulfport, United States",
    "Hattiesburg, United States",
    "Holly Springs, United States",
    "Jackson, United States",
    "Laurel, United States",
    "Meridian, United States",
    "Natchez, United States",
    "Ocean Springs, United States",
    "Oxford, United States",
    "Pascagoula, United States",
    "Pass Christian, United States",
    "Philadelphia, United States",
    "Port Gibson, United States",
    "Starkville, United States",
    "Tupelo, United States",
    "Vicksburg, United States",
    "West Point, United States",
    "Yazoo City, United States",
    "Missouri, United States",
    "Boonville, United States",
    "Branson, United States",
    "Cape Girardeau, United States",
    "Carthage, United States",
    "Chillicothe, United States",
    "Clayton, United States",
    "Columbia, United States",
    "Excelsior Springs, United States",
    "Ferguson, United States",
    "Florissant, United States",
    "Fulton, United States",
    "Hannibal, United States",
    "Independence, United States",
    "Jefferson City, United States",
    "Joplin, United States",
    "Kansas City, United States",
    "Kirksville, United States",
    "Lamar, United States",
    "Lebanon, United States",
    "Lexington, United States",
    "Maryville, United States",
    "Mexico, United States",
    "Monett, United States",
    "Neosho, United States",
    "New Madrid, United States",
    "Rolla, United States",
    "Saint Charles, United States",
    "Saint Joseph, United States",
    "Saint Louis, United States",
    "Sainte Genevieve, United States",
    "Salem, United States",
    "Sedalia, United States",
    "Springfield, United States",
    "Warrensburg, United States",
    "West Plains, United States",
    "Montana, United States",
    "Anaconda, United States",
    "Billings, United States",
    "Bozeman, United States",
    "Butte, United States",
    "Dillon, United States",
    "Fort Benton, United States",
    "Glendive, United States",
    "Great Falls, United States",
    "Havre, United States",
    "Helena, United States",
    "Kalispell, United States",
    "Lewistown, United States",
    "Livingston, United States",
    "Miles City, United States",
    "Missoula, United States",
    "Virginia City, United States",
    "Nebraska, United States",
    "Beatrice, United States",
    "Bellevue, United States",
    "Boys Town, United States",
    "Chadron, United States",
    "Columbus, United States",
    "Fremont, United States",
    "Grand Island, United States",
    "Hastings, United States",
    "Kearney, United States",
    "Lincoln, United States",
    "McCook, United States",
    "Minden, United States",
    "Nebraska City, United States",
    "Norfolk, United States",
    "North Platte, United States",
    "Omaha, United States",
    "Plattsmouth, United States",
    "Red Cloud, United States",
    "Sidney, United States",
    "Nevada, United States",
    "Boulder City, United States",
    "Carson City, United States",
    "Elko, United States",
    "Ely, United States",
    "Fallon, United States",
    "Genoa, United States",
    "Goldfield, United States",
    "Henderson, United States",
    "Las Vegas, United States",
    "North Las Vegas, United States",
    "Reno, United States",
    "Sparks, United States",
    "Virginia City, United States",
    "Winnemucca, United States",
    "New Hampshire, United States",
    "Berlin, United States",
    "Claremont, United States",
    "Concord, United States",
    "Derry, United States",
    "Dover, United States",
    "Durham, United States",
    "Exeter, United States",
    "Franklin, United States",
    "Hanover, United States",
    "Hillsborough, United States",
    "Keene, United States",
    "Laconia, United States",
    "Lebanon, United States",
    "Manchester, United States",
    "Nashua, United States",
    "Peterborough, United States",
    "Plymouth, United States",
    "Portsmouth, United States",
    "Rochester, United States",
    "Salem, United States",
    "Somersworth, United States",
    "New Jersey, United States",
    "Asbury Park, United States",
    "Atlantic City, United States",
    "Bayonne, United States",
    "Bloomfield, United States",
    "Bordentown, United States",
    "Bound Brook, United States",
    "Bridgeton, United States",
    "Burlington, United States",
    "Caldwell, United States",
    "Camden, United States",
    "Cape May, United States",
    "Clifton, United States",
    "Cranford, United States",
    "East Orange, United States",
    "Edison, United States",
    "Elizabeth, United States",
    "Englewood, United States",
    "Fort Lee, United States",
    "Glassboro, United States",
    "Hackensack, United States",
    "Haddonfield, United States",
    "Hoboken, United States",
    "Irvington, United States",
    "Jersey City, United States",
    "Lakehurst, United States",
    "Lakewood, United States",
    "Long Beach, United States",
    "Long Branch, United States",
    "Madison, United States",
    "Menlo Park, United States",
    "Millburn, United States",
    "Millville, United States",
    "Montclair, United States",
    "Morristown, United States",
    "Mount Holly, United States",
    "New Brunswick, United States",
    "New Milford, United States",
    "Newark, United States",
    "Ocean City, United States",
    "Orange, United States",
    "Parsippany–Troy Hills, United States",
    "Passaic, United States",
    "Paterson, United States",
    "Perth Amboy, United States",
    "Plainfield, United States",
    "Princeton, United States",
    "Ridgewood, United States",
    "Roselle, United States",
    "Rutherford, United States",
    "Salem, United States",
    "Somerville, United States",
    "South Orange Village, United States",
    "Totowa, United States",
    "Trenton, United States",
    "Union, United States",
    "Union City, United States",
    "Vineland, United States",
    "Wayne, United States",
    "Weehawken, United States",
    "West New York, United States",
    "West Orange, United States",
    "Willingboro, United States",
    "Woodbridge, United States",
    "New Mexico, United States",
    "Acoma, United States",
    "Alamogordo, United States",
    "Albuquerque, United States",
    "Artesia, United States",
    "Belen, United States",
    "Carlsbad, United States",
    "Clovis, United States",
    "Deming, United States",
    "Farmington, United States",
    "Gallup, United States",
    "Grants, United States",
    "Hobbs, United States",
    "Las Cruces, United States",
    "Las Vegas, United States",
    "Los Alamos, United States",
    "Lovington, United States",
    "Portales, United States",
    "Raton, United States",
    "Roswell, United States",
    "Santa Fe, United States",
    "Shiprock, United States",
    "Silver City, United States",
    "Socorro, United States",
    "Taos, United States",
    "Truth or Consequences, United States",
    "Tucumcari, United States",
    "New York, United States",
    "Albany, United States",
    "Amsterdam, United States",
    "Auburn, United States",
    "Babylon, United States",
    "Batavia, United States",
    "Beacon, United States",
    "Bedford, United States",
    "Binghamton, United States",
    "Bronx, United States",
    "Brooklyn, United States",
    "Buffalo, United States",
    "Chautauqua, United States",
    "Cheektowaga, United States",
    "Clinton, United States",
    "Cohoes, United States",
    "Coney Island, United States",
    "Cooperstown, United States",
    "Corning, United States",
    "Cortland, United States",
    "Crown Point, United States",
    "Dunkirk, United States",
    "East Aurora, United States",
    "East Hampton, United States",
    "Eastchester, United States",
    "Elmira, United States",
    "Flushing, United States",
    "Forest Hills, United States",
    "Fredonia, United States",
    "Garden City, United States",
    "Geneva, United States",
    "Glens Falls, United States",
    "Gloversville, United States",
    "Great Neck, United States",
    "Hammondsport, United States",
    "Harlem, United States",
    "Hempstead, United States",
    "Herkimer, United States",
    "Hudson, United States",
    "Huntington, United States",
    "Hyde Park, United States",
    "Ilion, United States",
    "Ithaca, United States",
    "Jamestown, United States",
    "Johnstown, United States",
    "Kingston, United States",
    "Lackawanna, United States",
    "Lake Placid, United States",
    "Levittown, United States",
    "Lockport, United States",
    "Mamaroneck, United States",
    "Manhattan, United States",
    "Massena, United States",
    "Middletown, United States",
    "Mineola, United States",
    "Mount Vernon, United States",
    "New Paltz, United States",
    "New Rochelle, United States",
    "New Windsor, United States",
    "New York City, United States",
    "Newburgh, United States",
    "Niagara Falls, United States",
    "North Hempstead, United States",
    "Nyack, United States",
    "Ogdensburg, United States",
    "Olean, United States",
    "Oneida, United States",
    "Oneonta, United States",
    "Ossining, United States",
    "Oswego, United States",
    "Oyster Bay, United States",
    "Palmyra, United States",
    "Peekskill, United States",
    "Plattsburgh, United States",
    "Port Washington, United States",
    "Potsdam, United States",
    "Poughkeepsie, United States",
    "Queens, United States",
    "Rensselaer, United States",
    "Rochester, United States",
    "Rome, United States",
    "Rotterdam, United States",
    "Rye, United States",
    "Sag Harbor, United States",
    "Saranac Lake, United States",
    "Saratoga Springs, United States",
    "Scarsdale, United States",
    "Schenectady, United States",
    "Seneca Falls, United States",
    "Southampton, United States",
    "Staten Island, United States",
    "Stony Brook, United States",
    "Stony Point, United States",
    "Syracuse, United States",
    "Tarrytown, United States",
    "Ticonderoga, United States",
    "Tonawanda, United States",
    "Troy, United States",
    "Utica, United States",
    "Watertown, United States",
    "Watervliet, United States",
    "Watkins Glen, United States",
    "West Seneca, United States",
    "White Plains, United States",
    "Woodstock, United States",
    "Yonkers, United States",
    "North Carolina, United States",
    "Asheboro, United States",
    "Asheville, United States",
    "Bath, United States",
    "Beaufort, United States",
    "Boone, United States",
    "Burlington, United States",
    "Chapel Hill, United States",
    "Charlotte, United States",
    "Concord, United States",
    "Durham, United States",
    "Edenton, United States",
    "Elizabeth City, United States",
    "Fayetteville, United States",
    "Gastonia, United States",
    "Goldsboro, United States",
    "Greensboro, United States",
    "Greenville, United States",
    "Halifax, United States",
    "Henderson, United States",
    "Hickory, United States",
    "High Point, United States",
    "Hillsborough, United States",
    "Jacksonville, United States",
    "Kinston, United States",
    "Kitty Hawk, United States",
    "Lumberton, United States",
    "Morehead City, United States",
    "Morganton, United States",
    "Nags Head, United States",
    "New Bern, United States",
    "Pinehurst, United States",
    "Raleigh, United States",
    "Rocky Mount, United States",
    "Salisbury, United States",
    "Shelby, United States",
    "Washington, United States",
    "Wilmington, United States",
    "Wilson, United States",
    "Winston-Salem, United States",
    "North Dakota, United States",
    "Bismarck, United States",
    "Devils Lake, United States",
    "Dickinson, United States",
    "Fargo, United States",
    "Grand Forks, United States",
    "Jamestown, United States",
    "Mandan, United States",
    "Minot, United States",
    "Rugby, United States",
    "Valley City, United States",
    "Wahpeton, United States",
    "Williston, United States",
    "Ohio, United States",
    "Akron, United States",
    "Alliance, United States",
    "Ashtabula, United States",
    "Athens, United States",
    "Barberton, United States",
    "Bedford, United States",
    "Bellefontaine, United States",
    "Bowling Green, United States",
    "Canton, United States",
    "Chillicothe, United States",
    "Cincinnati, United States",
    "Cleveland, United States",
    "Cleveland Heights, United States",
    "Columbus, United States",
    "Conneaut, United States",
    "Cuyahoga Falls, United States",
    "Dayton, United States",
    "Defiance, United States",
    "Delaware, United States",
    "East Cleveland, United States",
    "East Liverpool, United States",
    "Elyria, United States",
    "Euclid, United States",
    "Findlay, United States",
    "Gallipolis, United States",
    "Greenville, United States",
    "Hamilton, United States",
    "Kent, United States",
    "Kettering, United States",
    "Lakewood, United States",
    "Lancaster, United States",
    "Lima, United States",
    "Lorain, United States",
    "Mansfield, United States",
    "Marietta, United States",
    "Marion, United States",
    "Martins Ferry, United States",
    "Massillon, United States",
    "Mentor, United States",
    "Middletown, United States",
    "Milan, United States",
    "Mount Vernon, United States",
    "New Philadelphia, United States",
    "Newark, United States",
    "Niles, United States",
    "North College Hill, United States",
    "Norwalk, United States",
    "Oberlin, United States",
    "Painesville, United States",
    "Parma, United States",
    "Piqua, United States",
    "Portsmouth, United States",
    "Put-in-Bay, United States",
    "Salem, United States",
    "Sandusky, United States",
    "Shaker Heights, United States",
    "Springfield, United States",
    "Steubenville, United States",
    "Tiffin, United States",
    "Toledo, United States",
    "Urbana, United States",
    "Warren, United States",
    "Wooster, United States",
    "Worthington, United States",
    "Xenia, United States",
    "Yellow Springs, United States",
    "Youngstown, United States",
    "Zanesville, United States",
    "Oklahoma, United States",
    "Ada, United States",
    "Altus, United States",
    "Alva, United States",
    "Anadarko, United States",
    "Ardmore, United States",
    "Bartlesville, United States",
    "Bethany, United States",
    "Chickasha, United States",
    "Claremore, United States",
    "Clinton, United States",
    "Cushing, United States",
    "Duncan, United States",
    "Durant, United States",
    "Edmond, United States",
    "El Reno, United States",
    "Elk City, United States",
    "Enid, United States",
    "Eufaula, United States",
    "Frederick, United States",
    "Guthrie, United States",
    "Guymon, United States",
    "Hobart, United States",
    "Holdenville, United States",
    "Hugo, United States",
    "Lawton, United States",
    "McAlester, United States",
    "Miami, United States",
    "Midwest City, United States",
    "Moore, United States",
    "Muskogee, United States",
    "Norman, United States",
    "Oklahoma City, United States",
    "Okmulgee, United States",
    "Pauls Valley, United States",
    "Pawhuska, United States",
    "Perry, United States",
    "Ponca City, United States",
    "Pryor, United States",
    "Sallisaw, United States",
    "Sand Springs, United States",
    "Sapulpa, United States",
    "Seminole, United States",
    "Shawnee, United States",
    "Stillwater, United States",
    "Tahlequah, United States",
    "The Village, United States",
    "Tulsa, United States",
    "Vinita, United States",
    "Wewoka, United States",
    "Woodward, United States",
    "Oregon, United States",
    "Albany, United States",
    "Ashland, United States",
    "Astoria, United States",
    "Baker City, United States",
    "Beaverton, United States",
    "Bend, United States",
    "Brookings, United States",
    "Burns, United States",
    "Coos Bay, United States",
    "Corvallis, United States",
    "Eugene, United States",
    "Grants Pass, United States",
    "Hillsboro, United States",
    "Hood River, United States",
    "Jacksonville, United States",
    "John Day, United States",
    "Klamath Falls, United States",
    "La Grande, United States",
    "Lake Oswego, United States",
    "Lakeview, United States",
    "McMinnville, United States",
    "Medford, United States",
    "Newberg, United States",
    "Newport, United States",
    "Ontario, United States",
    "Oregon City, United States",
    "Pendleton, United States",
    "Port Orford, United States",
    "Portland, United States",
    "Prineville, United States",
    "Redmond, United States",
    "Reedsport, United States",
    "Roseburg, United States",
    "Salem, United States",
    "Seaside, United States",
    "Springfield, United States",
    "The Dalles, United States",
    "Tillamook, United States",
    "Pennsylvania, United States",
    "Abington, United States",
    "Aliquippa, United States",
    "Allentown, United States",
    "Altoona, United States",
    "Ambridge, United States",
    "Bedford, United States",
    "Bethlehem, United States",
    "Bloomsburg, United States",
    "Bradford, United States",
    "Bristol, United States",
    "Carbondale, United States",
    "Carlisle, United States",
    "Chambersburg, United States",
    "Chester, United States",
    "Columbia, United States",
    "Easton, United States",
    "Erie, United States",
    "Franklin, United States",
    "Germantown, United States",
    "Gettysburg, United States",
    "Greensburg, United States",
    "Hanover, United States",
    "Harmony, United States",
    "Harrisburg, United States",
    "Hazleton, United States",
    "Hershey, United States",
    "Homestead, United States",
    "Honesdale, United States",
    "Indiana, United States",
    "Jeannette, United States",
    "Jim Thorpe, United States",
    "Johnstown, United States",
    "Lancaster, United States",
    "Lebanon, United States",
    "Levittown, United States",
    "Lewistown, United States",
    "Lock Haven, United States",
    "Lower Southampton, United States",
    "McKeesport, United States",
    "Meadville, United States",
    "Middletown, United States",
    "Monroeville, United States",
    "Nanticoke, United States",
    "New Castle, United States",
    "New Hope, United States",
    "New Kensington, United States",
    "Norristown, United States",
    "Oil City, United States",
    "Philadelphia, United States",
    "Phoenixville, United States",
    "Pittsburgh, United States",
    "Pottstown, United States",
    "Pottsville, United States",
    "Reading, United States",
    "Scranton, United States",
    "Shamokin, United States",
    "Sharon, United States",
    "State College, United States",
    "Stroudsburg, United States",
    "Sunbury, United States",
    "Swarthmore, United States",
    "Tamaqua, United States",
    "Titusville, United States",
    "Uniontown, United States",
    "Warren, United States",
    "Washington, United States",
    "West Chester, United States",
    "Wilkes-Barre, United States",
    "Williamsport, United States",
    "York, United States",
    "Rhode Island, United States",
    "Barrington, United States",
    "Bristol, United States",
    "Central Falls, United States",
    "Cranston, United States",
    "East Greenwich, United States",
    "East Providence, United States",
    "Kingston, United States",
    "Middletown, United States",
    "Narragansett, United States",
    "Newport, United States",
    "North Kingstown, United States",
    "Pawtucket, United States",
    "Portsmouth, United States",
    "Providence, United States",
    "South Kingstown, United States",
    "Tiverton, United States",
    "Warren, United States",
    "Warwick, United States",
    "Westerly, United States",
    "Wickford, United States",
    "Woonsocket, United States",
    "South Carolina, United States",
    "Abbeville, United States",
    "Aiken, United States",
    "Anderson, United States",
    "Beaufort, United States",
    "Camden, United States",
    "Charleston, United States",
    "Columbia, United States",
    "Darlington, United States",
    "Florence, United States",
    "Gaffney, United States",
    "Georgetown, United States",
    "Greenville, United States",
    "Greenwood, United States",
    "Hartsville, United States",
    "Lancaster, United States",
    "Mount Pleasant, United States",
    "Myrtle Beach, United States",
    "Orangeburg, United States",
    "Rock Hill, United States",
    "Spartanburg, United States",
    "Sumter, United States",
    "Union, United States",
    "South Dakota, United States",
    "Aberdeen, United States",
    "Belle Fourche, United States",
    "Brookings, United States",
    "Canton, United States",
    "Custer, United States",
    "De Smet, United States",
    "Deadwood, United States",
    "Hot Springs, United States",
    "Huron, United States",
    "Lead, United States",
    "Madison, United States",
    "Milbank, United States",
    "Mitchell, United States",
    "Mobridge, United States",
    "Pierre, United States",
    "Rapid City, United States",
    "Sioux Falls, United States",
    "Spearfish, United States",
    "Sturgis, United States",
    "Vermillion, United States",
    "Watertown, United States",
    "Yankton, United States",
    "Tennessee, United States",
    "Alcoa, United States",
    "Athens, United States",
    "Chattanooga, United States",
    "Clarksville, United States",
    "Cleveland, United States",
    "Columbia, United States",
    "Cookeville, United States",
    "Dayton, United States",
    "Elizabethton, United States",
    "Franklin, United States",
    "Gallatin, United States",
    "Gatlinburg, United States",
    "Greeneville, United States",
    "Jackson, United States",
    "Johnson City, United States",
    "Jonesborough, United States",
    "Kingsport, United States",
    "Knoxville, United States",
    "Lebanon, United States",
    "Maryville, United States",
    "Memphis, United States",
    "Morristown, United States",
    "Murfreesboro, United States",
    "Nashville, United States",
    "Norris, United States",
    "Oak Ridge, United States",
    "Shelbyville, United States",
    "Tullahoma, United States",
    "Texas, United States",
    "Abilene, United States",
    "Alpine, United States",
    "Amarillo, United States",
    "Arlington, United States",
    "Austin, United States",
    "Baytown, United States",
    "Beaumont, United States",
    "Big Spring, United States",
    "Borger, United States",
    "Brownsville, United States",
    "Bryan, United States",
    "Canyon, United States",
    "Cleburne, United States",
    "College Station, United States",
    "Corpus Christi, United States",
    "Crystal City, United States",
    "Dallas, United States",
    "Del Rio, United States",
    "Denison, United States",
    "Denton, United States",
    "Eagle Pass, United States",
    "Edinburg, United States",
    "El Paso, United States",
    "Fort Worth, United States",
    "Freeport, United States",
    "Galveston, United States",
    "Garland, United States",
    "Goliad, United States",
    "Greenville, United States",
    "Harlingen, United States",
    "Houston, United States",
    "Huntsville, United States",
    "Irving, United States",
    "Johnson City, United States",
    "Kilgore, United States",
    "Killeen, United States",
    "Kingsville, United States",
    "Laredo, United States",
    "Longview, United States",
    "Lubbock, United States",
    "Lufkin, United States",
    "Marshall, United States",
    "McAllen, United States",
    "McKinney, United States",
    "Mesquite, United States",
    "Midland, United States",
    "Mission, United States",
    "Nacogdoches, United States",
    "New Braunfels, United States",
    "Odessa, United States",
    "Orange, United States",
    "Pampa, United States",
    "Paris, United States",
    "Pasadena, United States",
    "Pecos, United States",
    "Pharr, United States",
    "Plainview, United States",
    "Plano, United States",
    "Port Arthur, United States",
    "Port Lavaca, United States",
    "Richardson, United States",
    "San Angelo, United States",
    "San Antonio, United States",
    "San Felipe, United States",
    "San Marcos, United States",
    "Sherman, United States",
    "Sweetwater, United States",
    "Temple, United States",
    "Texarkana, United States",
    "Texas City, United States",
    "Tyler, United States",
    "Uvalde, United States",
    "Victoria, United States",
    "Waco, United States",
    "Weatherford, United States",
    "Wichita Falls, United States",
    "Ysleta, United States",
    "Utah, United States",
    "Alta, United States",
    "American Fork, United States",
    "Bountiful, United States",
    "Brigham City, United States",
    "Cedar City, United States",
    "Clearfield, United States",
    "Delta, United States",
    "Fillmore, United States",
    "Green River, United States",
    "Heber City, United States",
    "Kanab, United States",
    "Layton, United States",
    "Lehi, United States",
    "Logan, United States",
    "Manti, United States",
    "Moab, United States",
    "Monticello, United States",
    "Murray, United States",
    "Nephi, United States",
    "Ogden, United States",
    "Orderville, United States",
    "Orem, United States",
    "Panguitch, United States",
    "Park City, United States",
    "Payson, United States",
    "Price, United States",
    "Provo, United States",
    "Saint George, United States",
    "Salt Lake City, United States",
    "Spanish Fork, United States",
    "Springville, United States",
    "Tooele, United States",
    "Vernal, United States",
    "Vermont, United States",
    "Barre, United States",
    "Bellows Falls, United States",
    "Bennington, United States",
    "Brattleboro, United States",
    "Burlington, United States",
    "Essex, United States",
    "Manchester, United States",
    "Middlebury, United States",
    "Montpelier, United States",
    "Newport, United States",
    "Plymouth, United States",
    "Rutland, United States",
    "Saint Albans, United States",
    "Saint Johnsbury, United States",
    "Sharon, United States",
    "Winooski, United States",
    "Virginia, United States",
    "Abingdon, United States",
    "Alexandria, United States",
    "Bristol, United States",
    "Charlottesville, United States",
    "Chesapeake, United States",
    "Danville, United States",
    "Fairfax, United States",
    "Falls Church, United States",
    "Fredericksburg, United States",
    "Hampton, United States",
    "Hanover, United States",
    "Hopewell, United States",
    "Lexington, United States",
    "Lynchburg, United States",
    "Manassas, United States",
    "Martinsville, United States",
    "New Market, United States",
    "Newport News, United States",
    "Norfolk, United States",
    "Petersburg, United States",
    "Portsmouth, United States",
    "Reston, United States",
    "Richmond, United States",
    "Roanoke, United States",
    "Staunton, United States",
    "Suffolk, United States",
    "Virginia Beach, United States",
    "Waynesboro, United States",
    "Williamsburg, United States",
    "Winchester, United States",
    "Washington, United States",
    "Aberdeen, United States",
    "Anacortes, United States",
    "Auburn, United States",
    "Bellevue, United States",
    "Bellingham, United States",
    "Bremerton, United States",
    "Centralia, United States",
    "Coulee Dam, United States",
    "Coupeville, United States",
    "Ellensburg, United States",
    "Ephrata, United States",
    "Everett, United States",
    "Hoquiam, United States",
    "Kelso, United States",
    "Kennewick, United States",
    "Longview, United States",
    "Moses Lake, United States",
    "Oak Harbor, United States",
    "Olympia, United States",
    "Pasco, United States",
    "Point Roberts, United States",
    "Port Angeles, United States",
    "Pullman, United States",
    "Puyallup, United States",
    "Redmond, United States",
    "Renton, United States",
    "Richland, United States",
    "Seattle, United States",
    "Spokane, United States",
    "Tacoma, United States",
    "Vancouver, United States",
    "Walla Walla, United States",
    "Wenatchee, United States",
    "Yakima, United States",
    "West Virginia, United States",
    "Bath, United States",
    "Beckley, United States",
    "Bluefield, United States",
    "Buckhannon, United States",
    "Charles Town, United States",
    "Charleston, United States",
    "Clarksburg, United States",
    "Elkins, United States",
    "Fairmont, United States",
    "Grafton, United States",
    "Harpers Ferry, United States",
    "Hillsboro, United States",
    "Hinton, United States",
    "Huntington, United States",
    "Keyser, United States",
    "Lewisburg, United States",
    "Logan, United States",
    "Martinsburg, United States",
    "Morgantown, United States",
    "Moundsville, United States",
    "New Martinsville, United States",
    "Parkersburg, United States",
    "Philippi, United States",
    "Point Pleasant, United States",
    "Princeton, United States",
    "Romney, United States",
    "Shepherdstown, United States",
    "South Charleston, United States",
    "Summersville, United States",
    "Weirton, United States",
    "Welch, United States",
    "Wellsburg, United States",
    "Weston, United States",
    "Wheeling, United States",
    "White Sulphur Springs, United States",
    "Williamson, United States",
    "Wisconsin, United States",
    "Appleton, United States",
    "Ashland, United States",
    "Baraboo, United States",
    "Belmont, United States",
    "Beloit, United States",
    "Eau Claire, United States",
    "Fond du Lac, United States",
    "Green Bay, United States",
    "Hayward, United States",
    "Janesville, United States",
    "Kenosha, United States",
    "La Crosse, United States",
    "Lake Geneva, United States",
    "Madison, United States",
    "Manitowoc, United States",
    "Marinette, United States",
    "Menasha, United States",
    "Milwaukee, United States",
    "Neenah, United States",
    "New Glarus, United States",
    "Oconto, United States",
    "Oshkosh, United States",
    "Peshtigo, United States",
    "Portage, United States",
    "Prairie du Chien, United States",
    "Racine, United States",
    "Rhinelander, United States",
    "Ripon, United States",
    "Sheboygan, United States",
    "Spring Green, United States",
    "Stevens Point, United States",
    "Sturgeon Bay, United States",
    "Superior, United States",
    "Waukesha, United States",
    "Wausau, United States",
    "Wauwatosa, United States",
    "West Allis, United States",
    "West Bend, United States",
    "Wisconsin Dells, United States",
    "Wyoming, United States",
    "Buffalo, United States",
    "Casper, United States",
    "Cheyenne, United States",
    "Cody, United States",
    "Douglas, United States",
    "Evanston, United States",
    "Gillette, United States",
    "Green River, United States",
    "Jackson, United States",
    "Lander, United States",
    "Laramie, United States",
    "Newcastle, United States",
    "Powell, United States",
    "Rawlins, United States",
    "Riverton, United States",
    "Rock Springs, United States",
    "Sheridan, United States",
    "Ten Sleep, United States",
    "Thermopolis, United States",
    "Torrington, United States",
    "Worland, United States",
    
);

$item = '';


foreach ($array as &$value) { 

if(stripos($value, $_GET['query']) !== false){

    $item = $item . '"'.$value.'",';

}

}

foreach ($usArray as &$value) { 

    if(stripos($value, $_GET['query']) !== false){
    
        $item = $item . '"'.$value.'",';
    
    }
    
    }

$item =  rtrim($item,',');

echo '{"suggestions": ['.$item.']}';

?>